CREATE DATABASE walmart_db;
use walmart_db;
show tables;
select * from walmart_sales;

-- Business Problems

-- 1. Which product categories generate the highest revenue? List the top three categories by total sales.
select category, round(sum(sales),0) as total_sales from walmart_sales group by category order by total_sales desc limit 3;	

-- 2. What is the distribution of payment methods used by customers across all transactions?	
select payment_method, count(*) as cnt from walmart_sales group by payment_method order by cnt desc;

-- 3. Which branches are the top performers in terms of total revenue? Display the top three.	
select branch, round(sum(sales),0) as total_revenue from walmart_sales group by branch order by total_revenue desc limit 3;	

-- 4. Calculate the company's sales revenue year over year (YoY)?
with current_year as(
select year(date) as yr, round(sum(sales),0) as current_year_sales from walmart_sales
group by yr),
previous_year as(
select *,
lag(current_year_sales,1) over(order by yr) as previous_year_sales
from current_year)
select yr, current_year_sales, previous_year_sales,
concat(round(((current_year_sales - previous_year_sales)/previous_year_sales)*100,2),'%') as YoY_growth
 from previous_year;	
 
-- 5. What is the total revenue generated by each city? Which five cities lead in sales performance?
select city, round(sum(sales),0) as total_sales from walmart_sales group by city order by total_sales desc limit 5;		

-- 6. In each year, which month recorded the maximum total sales revenue?
with cte as(
select year(date) as yr, month(date) as mt, round(sum(sales),0) as total_sales from walmart_sales group by yr, mt order by yr,mt),
highest_sales_month as(
select *,
dense_rank() over(partition by yr order by total_sales desc) as rn
from cte)
select yr, mt, total_sales from highest_sales_month where rn = 1;

-- 7. Which product category has the highest number of orders placed?	
select category, count(*) as no_of_orders from walmart_sales group by category
order by no_of_orders desc;		
	
-- 8. Which product category has the highest average customer rating?
select category, round(avg(rating),1) as highest_avg_rating from walmart_sales group by category order by highest_avg_rating desc;			

-- 9. Find out in which quarter (Q1–Q4) the company makes the most revenue each year.
with quarter_sales as(
select year(date) as yr, quarter(date) as qt, round(sum(sales),0) as total_sales from walmart_sales group by yr, qt),
quarter_with_highest_sales as(
select *,
dense_rank() over(partition by yr order by yr asc, total_sales desc) as highest_sales_qt_rn
from quarter_sales)
select * from quarter_with_highest_sales where highest_sales_qt_rn = 1;
        		
-- 10. For each category, calculate the profit and rank them to identify the most profitable product category.
select category, round(sum(profit),0) as total_profit from walmart_sales group by category order by total_profit desc;

-- 11. For each product category, identify the top 3 performing branches in terms of total sales.
with top_3_branches as(
select category, branch, round(sum(sales),0) as total_sales from walmart_sales
group by category, branch),
highest_total_sales_branches as(
select *,
dense_rank() over(partition by category order by total_sales desc) as rn
from top_3_branches)
select * from highest_total_sales_branches where rn <= 3;

-- 12. For each branch, find out minimum, maximum and average rating for each category;
select branch, category, min(rating) as min_rating, max(rating) as max_rating, avg(rating) as avg_rating from walmart_sales group by branch, category order by branch;

-- 13. For each product category, calculate the total sales for every year to identify yearly trends in category performance.
select year(date) as year, 
round(sum(case when category = 'Health and Beauty' then sales end),0) as health_and_beauty,
round(sum(case when category = 'electronic accessories' then sales end),0) as electronic_accessories,
round(sum(case when category = 'Home and lifestyle' then sales end),0) as home_and_lifestyle,
round(sum(case when category = 'sports and travel' then sales end),0) as sports_and_travel,
round(sum(case when category = 'fashion accessories' then sales end),0) as fashion_accessories,
round(sum(case when category = 'food and beverages' then sales end),0) as food_and_beverages
 from walmart_sales group by year order by year;